export const CROP_VARIETIES = {
  Soybean: [
    "Tiwala 6",
    "Tiwala 8",
    "Tiwala 10",
    "Tiwala 12",
    "Tiwala 14",
    "Tiwala 20",
    "Tiwala 22",
    "Tiwala 24",
    "Tiwala 26",
    "Select Tudela Black",
    "Select Manchuria",
  ],
  Mungbean: [
    "Pagasa 1",
    "Pagasa 3",
    "Pagasa 5",
    "Pagasa 7",
    "Pagasa 9",
    "Pagasa 11",
    "Pagasa 15",
    "PHL 14295",
    "PHL 14296",
    "PHL 12636",
  ],
  Peanut: [
    "Biyaya 2",
    "Biyaya 4",
    "Biyaya 6",
    "Biyaya 8",
    "Biyaya 10",
    "Biyaya 12",
    "Biyaya 14",
    "Biyaya 16",
    "Sibalom",
  ],
};
